
sudo: required

services:
  - docker

before_install:
  - docker build -t coding4startups/docker-startup -f Dockerfile.dev .


script:
  - docker run coding4startups/docker-startup npm run test -- --coverage


